name: check lang

on:
  push:
  workflow_dispatch:

env:
  EXMENT_REPOSITORY: exceedone/exment
  EXMENT_REF: feature/laravel-12
  EXMENT_ADMIN_CORE_REPOSITORY: exceedone/exment-admin-core
  EXMENT_ADMIN_CORE_REF: master

jobs:
  check-lang:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: ${{ env.EXMENT_REPOSITORY }}
          ref: ${{ env.EXMENT_REF }}
          path: ./exment

      - uses: actions/checkout@v4
        with:
          repository: ${{ env.EXMENT_ADMIN_CORE_REPOSITORY }}
          ref: ${{ env.EXMENT_ADMIN_CORE_REF }}
          path: ./exment-admin-core

      - name: Link this repository into docker-exment as exment-boilerplate
        run: ln -s .. docker-exment/exment-boilerplate

      - name: Docker Compose Version
        run: docker compose --version

      - name: Make mysql up
        working-directory: docker-exment
        run: |
          make mysql-up

      - name: copy compose.dev.json
        working-directory: docker-exment
        run: |
          docker compose -f docker-compose.yml exec -T php cp composer.dev.json composer.json
          docker compose -f docker-compose.yml exec -T php cp composer.dev.lock composer.lock

      - name: Ensure safe git directory
        working-directory: docker-exment
        run: |
          docker compose -f docker-compose.yml exec -T php git config --global --add safe.directory '*'

      - name: Make mysql Initialize
        working-directory: docker-exment
        run: |
          make mysql-init

      - name: Run artisan exment:checklang
        working-directory: docker-exment
        run: |
          docker compose -f docker-compose.yml run -T php php artisan exment:checklang
